"""Constants used by Climate Control integration."""
DOMAIN = "climate_control"
CONF_CLIMATE_ENTITY = "climate_entity"
CONF_AREAS = "areas"
CONF_ZONES = "zones"
CONF_COVER_ENTITY = "cover_entity"
CONF_SENSOR_ENTITY = "sensor_entity"
CONF_AREA_FIXED = "fixed"
CONF_AREA = "area"
